[[redirects]]
from = "https://webdesight.com/*"
to = "https://www.webrebirth.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.webdesight.com/*"
to = "https://www.webrebirth.com/:splat"
status = 301
force = true


